### ISSUE TITLE
Error when run front-end app

### ISSUE THREAD

**Issue by vliam0602** [zalopay-samples/quickstart-node-disbursement#4]
Hi, I got this error when I try to run the command "npm run frontend"

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\project\references\quickstart-disbursement-main\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\project\references\quickstart-disbursement-main\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\project\references\quickstart-disbursement-main\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\project\references\quickstart-disbursement-main\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\project\references\quickstart-disbursement-main\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\project\references\quickstart-disbursement-main\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\project\references\quickstart-disbursement-main\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\project\references\quickstart-disbursement-main\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
D:\project\references\quickstart-disbursement-main\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\project\references\quickstart-disbursement-main\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\project\references\quickstart-disbursement-main\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\project\references\quickstart-disbursement-main\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\project\references\quickstart-disbursement-main\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\project\references\quickstart-disbursement-main\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\project\references\quickstart-disbursement-main\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\project\references\quickstart-disbursement-main\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\project\references\quickstart-disbursement-main\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.18.2

**Comment by anhldbk** [comment]
@vliam0206 Hi Lam, the error code looks related to OpenSSL. See:

https://stackoverflow.com/questions/75959563/node-js-err-ossl-evp-unsupported-error-when-running-npm-run-start
